version: '2'

services:
  app:
    image: 'spring:latest'
    build:
      context: .
    ports:
      - 8080:8080
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.hibernate.dialect.PostgreSQLDialect
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test